Repository codestates-seb/seb40_main_010, pull requests merged in 2022-12, with the labels that each got.

#302 ✨ feat : reserveController 수정 테스트 코드 작성
  server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java
  server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java
  server/src/main/java/com/main10/domain/reserve/entity/Reserve.java
  server/src/test/java/com/main10/reserve/controller/ReservePatchTest.java
  server/src/test/java/com/main10/review/controller/ReviewPatchTest.java
Labels: ✅ Test

#303 ♻️ refactor : DTO 수정, Test코드 작성
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/main10/domain/place/controller/PlaceController.java
  server/src/main/java/com/main10/domain/place/dto/PlaceDto.java
  server/src/main/java/com/main10/domain/place/dto/PlaceImageDto.java
  server/src/main/java/com/main10/domain/place/dto/PlaceImageResponseDto.java
  server/src/main/java/com/main10/domain/place/dto/PlacePatchDto.java
  server/src/main/java/com/main10/domain/place/dto/PlacePostDto.java
  server/src/main/java/com/main10/domain/place/dto/PlaceResponseDto.java
  server/src/main/java/com/main10/domain/place/service/PlaceDbService.java
  server/src/main/java/com/main10/domain/place/service/PlaceImageService.java
  server/src/main/java/com/main10/domain/place/service/PlaceService.java
  server/src/test/java/com/main10/place/controller/PlaceGetTest.java
  server/src/test/java/com/main10/place/controller/PlacePatchTest.java
  server/src/test/java/com/main10/place/controller/PlacePostTest.java
Labels: 🔨 Refactor

#304 🐛 fix : 무한 스크롤 버튼 호환, 뒤로가기, mbti 로그인 유무 수정
  client/src/App.js
  client/src/components/MbtiPlaces.js
  client/src/components/Navigation/Nav.js
  client/src/components/Navigation/NavButton.js
  client/src/components/Place.js
  client/src/pages/Detail.js
  client/src/pages/Places.js
  client/src/pages/SignUp.js
  client/src/setUpProxy.js
  client/src/utils/carouselSetting.js
  client/src/utils/categoryButton.js
  client/src/utils/categoryData.js
Labels: 🚨 BugFix, 👽️ API

#307 ♻️ refactor: Reserve Test 코드 정렬 및 Place Test endTime 추가
  server/src/test/java/com/main10/place/controller/PlacePatchTest.java
  server/src/test/java/com/main10/reserve/controller/ReservePatchTest.java
  server/src/test/java/com/main10/reserve/controller/ReservePaymentTest.java
  server/src/test/java/com/main10/review/controller/ReviewControllerTest.java
  server/src/test/java/com/main10/review/controller/ReviewDeleteTest.java
  server/src/test/java/com/main10/review/controller/ReviewGetTest.java
  server/src/test/java/com/main10/review/controller/ReviewPatchTest.java
  server/src/test/java/com/main10/review/controller/ReviewPostTest.java
Labels: ✅ Test

#306 🐛 fix : payment 헤더 수정
  client/src/components/ReservationComponents/useReservation.js
Labels: 🚨 BugFix

#308 🎨 style : 스타일 변경
  client/public/logo1.png
  client/public/logo3.png
  client/src/atoms.js
  client/src/components/Category.js
  client/src/components/Fade.js
  client/src/components/Map.js
  client/src/components/MbtiPlaces.js
  client/src/components/MyPageComponents/MyPageCategoryList.js
  client/src/components/MyPageComponents/MyPageComponent.js
  client/src/components/Navigation/Nav.js
  client/src/components/Navigation/NavButton.js
  client/src/components/Place.js
  client/src/components/RegisterComponents/RegisterCategory.js
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/components/ReservationComponents/ReservationCalendar.js
  client/src/components/ReservationComponents/ReservationCapacityHandler.js
  client/src/components/ReviewComponents/Review.js
  client/src/components/ReviewComponents/ReviewContainer.js
  client/src/components/View.js
  client/src/hooks/useLogin.js
  client/src/pages/Detail.js
  client/src/pages/LogIn.js
  client/src/pages/MyPage.js
  client/src/pages/Places.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
  client/src/utils/categoryButton.js
Labels: 🖼 HTML&CSS

#309 🐛 fix : 로그아웃 observer 오류 수정
  client/src/components/Navigation/NavButton.js
  client/src/pages/Places.js
Labels: 🚨 BugFix

#310 :art: 디자인 수정
  client/src/components/RegisterComponents/RegisterCategory.js
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/components/ReservationComponents/useReservation.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: 🖼 HTML&CSS

#311 :art: style : 로그인, 회원가입, 글 등록 디자인 수정
  client/src/pages/LogIn.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: 🖼 HTML&CSS

#312 ✨ feat: Reserve Test 예약 프로세스2, 3 구현
  server/src/docs/asciidoc/index.adoc
  server/src/main/java/com/main10/domain/member/dto/AuthDto.java
  server/src/main/java/com/main10/domain/member/dto/MemberDto.java
  server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java
  server/src/main/java/com/main10/domain/reserve/service/ReserveService.java
  server/src/test/java/com/main10/reserve/controller/ReserveControllerTest.java
  server/src/test/java/com/main10/reserve/controller/ReservePaymentTest.java
Labels: ✅ Test, 🔨 Refactor

#313 ✨ feat : AuthController 테스트 코드 작성중
  server/src/main/java/com/main10/ServerApplication.java
  server/src/main/java/com/main10/domain/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/main10/domain/member/controller/AuthController.java
  server/src/main/java/com/main10/domain/member/dto/AuthDto.java
  server/src/main/java/com/main10/domain/member/dto/TokenDto.java
  server/src/main/java/com/main10/domain/member/service/AuthService.java
  server/src/main/java/com/main10/domain/place/dto/PlaceCategoryDto.java
  server/src/main/java/com/main10/domain/place/dto/PlaceDto.java
  server/src/main/java/com/main10/domain/place/entity/Place.java
  server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java
  server/src/main/java/com/main10/domain/reserve/service/ReserveService.java
  server/src/main/java/com/main10/domain/review/dto/ReviewDto.java
  server/src/main/java/com/main10/global/config/RedisInitializeConfig.java
  server/src/test/java/com/main10/ServerApplicationTests.java
  server/src/test/java/com/main10/member/auth/controller/AuthControllerTest.java
  server/src/test/java/com/main10/member/auth/controller/LoginTest.java
  server/src/test/java/com/main10/member/auth/controller/LogoutTest.java
  server/src/test/java/com/main10/member/auth/controller/ReIssueTest.java
  server/src/test/java/com/main10/member/member/controller/MemberControllerTest.java
  server/src/test/java/com/main10/reserve/controller/ReserveControllerTest.java
Labels: ✅ Test

#314 📝 docs : 주석 제거
  client/src/App.js
  client/src/components/Category.js
  client/src/components/MbtiPlaces.js
  client/src/components/Navigation/Nav.js
  client/src/components/Navigation/NavButton.js
  client/src/components/Navigation/NavUtils.js
  client/src/components/Place.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/Places.js
  client/src/utils/categoryButton.js
  client/src/utils/payment.js
Labels: 📄 Docs

#316 🐛 fix : AuthDto 충돌 수정
  server/src/main/java/com/main10/domain/member/dto/AuthDto.java
  server/src/main/java/com/main10/domain/member/service/AuthService.java
  server/src/test/java/com/main10/member/auth/controller/ReIssueTest.java
Labels: 🚨 BugFix

#315 ♻️ refactor : 콘솔로그 제거 및 ui 수정
  client/src/components/MyPageComponents/MyPageCategoryList.js
  client/src/components/MyPageComponents/MyPageComponent.js
  client/src/components/ReviewComponents/ReviewContainer.js
  client/src/components/ReviewComponents/ReviewWrite.js
  client/src/hooks/useMyPage.js
  client/src/hooks/useRegisterEdit.js
Labels: 🔨 Refactor, 🖼 HTML&CSS

#319 ♻️ refactor : reviewController GET 테스트 코드 수정
  server/src/main/java/com/main10/domain/review/entity/Review.java
  server/src/main/java/com/main10/global/util/Auditable.java
  server/src/test/java/com/main10/review/controller/ReviewControllerTest.java
  server/src/test/java/com/main10/review/controller/ReviewGetTest.java
Labels: ✅ Test

#320 ♻️ refactor: Place Dto 유효성 검증, Review Service 주석 수정
  server/src/main/java/com/main10/domain/place/dto/PlaceDto.java
  server/src/main/java/com/main10/domain/place/service/PlaceService.java
  server/src/main/java/com/main10/domain/review/service/ReviewService.java
  server/src/test/java/com/main10/reserve/controller/ReserveGetTest.java
Labels: 🔨 Refactor

#321 ✨ feat : Dto validator 추가 작성
  server/src/main/java/com/main10/domain/member/controller/AuthController.java
  server/src/main/java/com/main10/domain/member/dto/AuthDto.java
  server/src/main/java/com/main10/domain/member/dto/MemberDto.java
  server/src/main/java/com/main10/domain/member/dto/TokenDto.java
  server/src/main/java/com/main10/domain/member/service/AuthService.java
  server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java
  server/src/main/java/com/main10/domain/reserve/service/ReserveService.java
  server/src/main/java/com/main10/domain/review/dto/ReviewDto.java
  server/src/main/java/com/main10/global/batch/dto/Mbti.java
  server/src/main/java/com/main10/global/security/resolver/CustomArgumentResolver.java
  server/src/test/java/com/main10/member/auth/controller/AuthControllerTest.java
Labels: ⛲ Feature

#322 :recycle: refactor 회원가입 페이지 수정
  client/src/hooks/useSignUp.js
  client/src/pages/SignUp.js
Labels: 🔨 Refactor

#336 👽 api : 서버 주소 변경
  client/src/App.js
  client/src/components/MbtiPlaces.js
  client/src/components/MyPageComponents/MyPageCategoryList.js
  client/src/components/Navigation/NavButton.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/components/ReservationComponents/useReservation.js
  client/src/components/ReviewComponents/ReviewContainer.js
  client/src/components/ReviewComponents/ReviewWrite.js
  client/src/hooks/useLogin.js
  client/src/hooks/useMyPage.js
  client/src/hooks/useRegister.js
  client/src/hooks/useRegisterEdit.js
  client/src/hooks/useSignUp.js
  client/src/pages/Detail.js
  client/src/pages/Places.js
Labels: 👽️ API

#346 로그인, 회원가입 페이지 한글로 수정
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: 🖼 HTML&CSS

#350 🐛 fix : s3 이미지 업로드 수정
  .github/workflows/aws.yml
  .github/workflows/gradle.yml
  README.md
  server/build.gradle
  server/buildspec.yml
  server/images/13434963610541.jpg
  server/images/13434990555250.jpg
  server/images/13434990761625.jpg
  server/scripts/server_start.sh
  server/src/main/java/com/main10/domain/member/dto/MemberDto.java
  server/src/main/java/com/main10/domain/place/controller/PlaceController.java
  server/src/main/java/com/main10/domain/place/dto/PlaceCategoryDto.java
  server/src/main/java/com/main10/domain/place/dto/PlaceDto.java
  server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java
  server/src/main/java/com/main10/domain/reserve/entity/Reserve.java
  server/src/main/java/com/main10/domain/review/dto/ReviewDto.java
  server/src/main/java/com/main10/global/batch/dto/Mbti.java
  server/src/main/java/com/main10/global/security/config/SecurityConfig.java
  server/src/main/java/com/main10/global/security/config/WebMvcConfig.java
  server/src/main/java/com/main10/global/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/main10/global/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/main10/global/security/token/JwtAuthenticationToken.java
  server/src/main/java/com/main10/global/security/utils/AuthConstants.java
  server/src/main/java/com/main10/global/security/utils/JwtTokenUtils.java
  server/src/main/resources/application-server.yml
  server/src/main/resources/bootstrap.yml
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/main10/ServerApplicationTests.java
  server/src/test/java/com/main10/member/member/controller/MemberControllerTest.java
Labels: 🚨 BugFix

#353 👽 api : api 주소 수정
  client/src/components/MyPageComponents/MyPageCategoryList.js
  client/src/components/ReviewComponents/ReviewContainer.js
  client/src/components/ReviewComponents/ReviewWrite.js
  client/src/utils/Modal.js
Labels: 👽️ API

#362 ✨ feat : 마이페이지 프로필 디자인 및 api 수정
  client/src/components/MyPageComponents/MyPageComponent.js
  client/src/hooks/useMyPage.js
Labels: 🖼 HTML&CSS, 👽️ API

#369 :bug: fix : 링크 복사 기능 오류 수정
  client/package-lock.json
  client/package.json
  client/src/components/ReservationComponents/ReservationBottomButtons.js
Labels: 🚨 BugFix

#371 :bug: fix : 예약 총인원수 블록
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/ReservationComponents/ReservationCapacityHandler.js
  client/src/pages/Detail.js
Labels: 🚨 BugFix

#375 :bug: fix : 총 인원 오류 수정
  client/src/atoms.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/ReservationComponents/ReservationCapacityHandler.js
  client/src/pages/Detail.js
Labels: 🚨 BugFix

#381 ♻️ refactor : 콘솔로그 제거
  client/src/components/MyPageComponents/MyPageCategoryList.js
  client/src/components/Place.js
Labels: 🔨 Refactor

#382 🐛 fix : 리뷰작성일자 오류 수정
  client/src/components/ReviewComponents/Review.js
Labels: 🚨 BugFix

#384 🐛 fix : 리뷰 표기 오류 수정
  client/src/components/ReviewComponents/Review.js
Labels: 🚨 BugFix

#388 🐛 fix : 마이페이지 border 및 리뷰 날짜 표기 수정
  client/src/components/MyPageComponents/MyPageComponent.js
  client/src/components/ReviewComponents/Review.js
Labels: 🚨 BugFix, 🖼 HTML&CSS

#390 :sparkles: feat : 스크롤 최상단으로 이동
  client/src/components/ScrollToTop.js
  client/src/index.js
Labels: ⛲ Feature

#391 :bug: fix: 예약시간 블럭 오류 수정
  client/src/components/ReservationComponents/useCalendar.js
Labels: 🚨 BugFix

#392 ♻️ refactor : 리뷰 날짜 표기 수정
  client/src/components/MyPageComponents/MyPageCategoryList.js
Labels: 🔨 Refactor

#393 :recycle: refactor :input 이전기록 삭제
  client/src/pages/Register.js
Labels: 🔨 Refactor

#394 :recycle: refactor : 장소등록 페이지 이동시 최대인원 초기화
  client/src/components/Navigation/NavButton.js
  client/src/hooks/useRegister.js
Labels: 🔨 Refactor

#398 👷 build : 개발용 서버 파일 배포
  server/src/main/java/com/main10/domain/bookmark/controller/BookmarkController.java
  server/src/main/java/com/main10/domain/bookmark/service/BookmarkService.java
  server/src/main/java/com/main10/global/security/config/SecurityConfig.java
  server/src/main/resources/static/docs/index.html
  server/src/test/java/com/main10/review/controller/ReviewGetTest.java
Labels: ⚙Setting

#399 ♻️ refactor : 북마크 헤더값 수정 및 콘솔로그 제거
  client/src/App.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
Labels: 🚨 BugFix, 🔨 Refactor, 👽️ API

#400 ✨ feat : 결제 상태 추가
  client/src/components/MyPageComponents/MyPageCategoryList.js
Labels: 👽️ API

#401 회원가입 핸드폰번호 정규식 변경
  client/src/pages/SignUp.js
Labels: 🚨 BugFix

#403 ♻️ refactor : memberDto 핸드폰번호 정규식 수정
  server/src/main/java/com/main10/domain/member/dto/MemberDto.java
  server/src/main/resources/static/docs/index.html
Labels: 🔨 Refactor, ⛲ Feature

#404 로그아웃 상태에서 북마크 클릭시 로그인 페이지로 이동
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/components/ReservationComponents/useReservation.js
Labels: ⛲ Feature

#405 로그아웃 상태에서 예약버튼 클릭시 경고창 기능 추가
  client/src/components/ReservationComponents/useReservation.js
Labels: ⛲ Feature

#406 글 등록 오류 수정
  client/src/hooks/useRegister.js
  client/src/pages/Register.js
Labels: 🚨 BugFix

#407 ✨ feat : 검색어 잔류
  client/src/components/Navigation/Nav.js
  client/src/pages/Places.js
Labels: ⛲ Feature

#408 Quartz614 patch 2
  README.md
Labels: 📄 Docs

#411 Update README.md
  README.md
Labels: 📄 Docs

#414 :recycle: refactor : 카카오 oauth 로그인 구현
  client/package.json
  client/public/btn_google_signin_light_focus_web.png
  client/public/btn_google_signin_light_focus_web@2x.png
  client/public/kakao_login_medium_narrow.png
  client/src/App.js
  client/src/components/Loading.js
  client/src/components/Login/GoogleLogin.js
  client/src/components/Login/KakaoLogin.js
  client/src/components/Login/OAuth2RedirectHandler.js
  client/src/pages/LogIn.js
Labels: 🔨 Refactor

#418 ✨ feat : POSTMAN 장소 삭제 및 호스트가 예약 내역 조회
  server/src/main/java/com/main10/domain/place/controller/PlaceController.java
  server/src/main/java/com/main10/domain/place/service/PlaceService.java
  server/src/main/java/com/main10/domain/reserve/controller/ReserveController.java
  server/src/main/java/com/main10/domain/reserve/dto/ReserveDto.java
  server/src/main/java/com/main10/domain/reserve/repository/CustomReserveRepository.java
  server/src/main/java/com/main10/domain/reserve/repository/ReserveRepositoryImpl.java
  server/src/main/java/com/main10/domain/reserve/service/ReserveDbService.java
  server/src/main/java/com/main10/domain/reserve/service/ReserveService.java
Labels: ⛲ Feature

#419 :bug: fix : 소셜로그인 mbti 반영
  client/src/components/Login/OAuth2RedirectHandler.js
  client/src/pages/SignUp.js
Labels: 🚨 BugFix

#420 :bug: fix : 소셜로그인 mbti 반영 오류 수정
  client/public/index.html
  client/src/components/Login/OAuth2RedirectHandler.js
Labels: 🚨 BugFix

#421 :recycle: refactor: 메서드 변경 및 콘솔 제거
  client/src/components/Login/OAuth2RedirectHandler.js
Labels: 🔨 Refactor

#422 :bug: fix : 소셜로그인 토큰 오류 수정
  client/src/components/Login/OAuth2RedirectHandler.js
Labels: 🚨 BugFix

#423 :bug: fix : 권한 없을 시 강제 로그아웃
  client/src/components/Navigation/NavButton.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
Labels: 🚨 BugFix

#424 권한없이 북마크 클릭시 경고창 생성
  client/src/components/ReservationComponents/ReservationBottomButtons.js
Labels: 🚨 BugFix

#425 로그인, 회원가입 버튼 커서 변경
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: 🖼 HTML&CSS

#427 Update README.md
  README.md
Labels: 📄 Docs
