Repository codestates-seb/seb40_main_010, pull requests merged in 2022-11, with the labels that each got.

#2 🔖 release : front 초기세팅
  client/.eslintrc.js
  client/.gitignore
  client/.prettierrc.js
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/src/App.js
  client/src/atoms.js
  client/src/components/Nav.js
  client/src/index.js
  client/src/pages/Detail.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: ⚙Setting

#8 📝 docs : eslint props rules 오류 수정
  client/.eslintrc.js
Labels: 🚨 BugFix, 📄 Docs

#12 ✨ feat : 토큰 엔티티 추가
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/settings.gradle
  server/src/main/java/com/main21/ServerApplication.java
  server/src/main/java/com/main21/bookmark/entity/Bookmark.java
  server/src/main/java/com/main21/member/entity/MBTI.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/entity/Token.java
  server/src/main/java/com/main21/place/entity/Category.java
  server/src/main/java/com/main21/place/entity/MBTICount.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/entity/PlaceCategory.java
  server/src/main/java/com/main21/place/entity/PlaceImage.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/review/entity/Review.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
  server/src/test/java/com/main21/ServerApplicationTests.java
Labels: ⛲ Feature

#14 ✨ feat : Member Entity 작성
  server/src/main/java/com/main21/ServerApplication.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/entity/MBTI.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/util/Auditable.java
Labels: ⛲ Feature

#16 🐛 fix : Member Entity 오타 수정
  server/src/main/java/com/main21/member/entity/MBTI.java
Labels: ⛲ Feature

#17 🐛 fix : 패키지변경 및 연관관계매핑수정
  server/src/main/java/com/main21/member/entity/MBTI.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/entity/Token.java
Labels: 🔨 Refactor

#19 🐛 fix : place 로직 수정
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/mapper/PlaceMapper.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: 🔨 Refactor

#20 ✨ feat : Reserve Create 생성
  server/src/main/java/com/main21/place/repository/PlaceRepository.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/mapper/ReserveMapper.java
  server/src/main/java/com/main21/reserve/repository/ReserveRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature

#21 ✨ feat : Member 연관관계 작성 완료
  server/src/main/java/com/main21/member/entity/MBTI.java
  server/src/main/java/com/main21/member/entity/Member.java
Labels: ⛲ Feature

#22 🐛 fix : place 연관관계 생성
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
Labels: ⛲ Feature

#25 ✨ feat : Member Dto 작성
  server/src/main/java/com/main21/member/dto/MemberDto.java
Labels: ⛲ Feature

#26 🐛 fix : AuthDto Response 빌더 패턴 추가
  server/src/main/java/com/main21/member/dto/AuthDto.java
Labels: 🔨 Refactor

#27 🐛 fix : AuthDto 수정 요청사항 반영
  server/src/main/java/com/main21/member/dto/AuthDto.java
Labels: 🔨 Refactor

#30 ✨ feat : Review Dto 작성
  server/src/main/java/com/main21/review/entity/dto/ReviewDto.java
Labels: ⛲ Feature

#31 ✨ feat : 북마크 Dto 추가
  server/src/main/java/com/main21/bookmark/dto/BookmarkDto.java
Labels: ⛲ Feature

#33 ✨ feat: Place, PlaceCategory 연관관계 매핑
  server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/entity/PlaceCategory.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature

#32 ✨ feat: Reserve Place 매핑
  server/build.gradle
  server/src/main/java/com/main21/place/entity/Category.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/db/h2/CategoryData.sql
Labels: ⛲ Feature

#37 sparkles feat : 로그인페이지 구현
  client/src/pages/LogIn.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#40 ♻️ refactor : review 연관관계 수정
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/review/entity/Review.java
Labels: 🔨 Refactor

#42 ✨ feat : PlaceImage 사진 업로드
  server/build.gradle
  server/images;20221114/181134213335600.png
  server/images;20221114/181134253735500.png
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceImageDto.java
  server/src/main/java/com/main21/place/dto/PlacePostDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/entity/PlaceImage.java
  server/src/main/java/com/main21/place/repository/PlaceImageRepository.java
  server/src/main/java/com/main21/place/service/FileHandler.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/resources/application-local.yml
Labels: 👽️ API

#44 👷 build : yml 파일 삭제
  server/.gitignore
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/mapper/PlaceMapper.java
  server/src/main/java/com/main21/place/service/FileHandler.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/resources/application-server.yml
Labels: ⚙Setting

#45 👷 build : ignore 파일수정
  server/.gitignore
  server/src/main/resources/application-local.yml
Labels: 🔨 Refactor

#46 ✨ feat : nav mockup
  client/src/components/Nav.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#47 ✨ feat : 리뷰 작성 모달창 제작
  client/src/components/ReviewWrite.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#48 ✨ feat : 마이페이지 모달 창 제작
  client/src/components/Modal.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#49 ✨ feat : review 등록, 수정, 삭제 구현 (조회 구현 해야함)
  server/build.gradle
  server/src/main/java/com/main21/exception/ExceptionCode.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/repository/MemberRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/review/entity/Review.java
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepository.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature

#52 ✨ feat : exception 코드 작성
  server/src/main/java/com/main21/exception/ExceptionController.java
  server/src/main/java/com/main21/exception/Response.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
Labels: ⛲ Feature

#54 ✨ feat : Bookmark 기능 구현
  server/src/main/java/com/main21/bookmark/controller/BookmarkController.java
  server/src/main/java/com/main21/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/main21/bookmark/entity/Bookmark.java
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/main21/bookmark/repository/CustomBookmarkRepository.java
  server/src/main/java/com/main21/bookmark/service/BookmarkService.java
  server/src/main/java/com/main21/dto/MultiResponseDto.java
  server/src/main/java/com/main21/dto/PageInfo.java
  server/src/main/java/com/main21/dto/SingleResponseDto.java
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/repository/ReviewRepository.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#55 ✨ feat : Reserve 등록, 수정 구현
  server/images;20221114/181134213335600.png
  server/images;20221114/181134253735500.png
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature, 👽️ API

#56 ♻️ refactor : Bookmark 기능 구현 수정2
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/main21/bookmark/repository/CustomBookmarkRepository.java
  server/src/main/java/com/main21/bookmark/service/BookmarkService.java
Labels: 🔨 Refactor

#59 ♻️ refactor : @CreatedDate 추가
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
Labels: 🔨 Refactor

#60 ✨ feat : 상세페이지 리뷰 조회 구현
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#61 ♻️ refactor : Review Service 수정
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#62 ♻️ refactor : ReviewRepositoryImpl 수정
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
Labels: ⛲ Feature, 👽️ API

#63 ✨ feat : 회원가입 구현
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/member/repository/MemberRepository.java
  server/src/main/java/com/main21/member/service/MemberService.java
Labels: ⛲ Feature, 👽️ API

#66 🐛 fix : 충돌 수정
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: 🚨 BugFix

#67 🐛 fix : 충돌 수정 2
  server/src/main/java/com/main21/member/repository/MemberRepository.java
Labels: 🚨 BugFix

#68 🐛 fix : 코드 오류 수정
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
Labels: 🚨 BugFix

#71 ✨ feat : 예약 삭제(취소) 기능 구현
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature, 👽️ API

#72 ✨ feat : member 정보 수정 구현
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/service/MemberService.java
Labels: ⛲ Feature, 👽️ API

#74 ♻️ refactor : MemberController url 변경
  server/src/main/java/com/main21/member/controller/MemberController.java
Labels: 🔨 Refactor

#78 ✨ feat : 공간 조회 기능 구현
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceCategoryDto.java
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/entity/PlaceCategory.java
  server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java
  server/src/main/java/com/main21/place/repository/PlaceRepository.java
  server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature, 👽️ API

#82 :sparkles: feat : 글 등록 페이지 구현
  client/.eslintrc.js
  client/db.json
  client/fake-server/db.json
  client/package-lock.json
  client/package.json
  client/src/atoms.js
  client/src/pages/LogIn.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#83 ✨ feat : 모달창에 기능 추가
  client/src/components/Modal.js
Labels: ⛲ Feature

#81 ✨ feat : Reserve, Review patch,Delete CookieValue 추가
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: 🔨 Refactor, ⛲ Feature, 👽️ API

#84 ✨ feat : 모달창 상태 기능 추가
  client/src/components/Modal.js
Labels: ⛲ Feature

#85 ✨ feat : nav api 요청 시 배열과 텍스트 위치 변경
  client/src/components/Nav.js
Labels: ⛲ Feature

#86 ✨ feat : 리뷰작성창 모달 기능 구현 및 props연결
  client/src/components/ReviewWrite.js
Labels: ⛲ Feature

#88 ✨ feat : 공간 조회 및 검색 기능 구현
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java
  server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature, 👽️ API

#89 ✨ feat : 시큐리티 로그인/로그아웃 기능 구현
  server/build.gradle
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/AuthDto.java
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/member/entity/Token.java
  server/src/main/java/com/main21/member/repository/TokenRepository.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/member/service/MemberService.java
  server/src/main/java/com/main21/member/utils/AuthConstant.java
  server/src/main/java/com/main21/security/config/AuthenticationManagerConfig.java
  server/src/main/java/com/main21/security/config/CustomFilterConfig.java
  server/src/main/java/com/main21/security/config/RedisConfig.java
  server/src/main/java/com/main21/security/config/SecurityConfig.java
  server/src/main/java/com/main21/security/details/MemberDetailService.java
  server/src/main/java/com/main21/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main21/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/main21/security/handler/JwtAccessDeniedHandler.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main21/security/utils/CookieUtils.java
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
  server/src/main/java/com/main21/security/utils/RedisUtils.java
Labels: ⛲ Feature

#91 ✨ feat : detail 컴포넌트 구현
  client/.gitignore
  client/src/atoms.js
  client/src/components/Fade.js
  client/src/components/Map.js
  client/src/components/View.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#90 ✨ feat : category 구현
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/Category.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#93 ♻️ refactor : Bookmark Pagination 적용
  server/src/main/java/com/main21/bookmark/controller/BookmarkController.java
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java
  server/src/main/java/com/main21/bookmark/repository/CustomBookmarkRepository.java
  server/src/main/java/com/main21/bookmark/service/BookmarkService.java
Labels: 🔨 Refactor

#95 ✨ feat : Member 이미지 업로드 구현
  server/src/main/java/com/main21/file/S3Upload.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/entity/MemberImage.java
  server/src/main/java/com/main21/member/repository/MemberImageRepository.java
  server/src/main/java/com/main21/member/service/MemberService.java
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature, 👽️ API

#97 ✨ feat : 유저이미지 S3 업로드 구현, 코드 리팩토링
  server/src/main/java/com/main21/file/S3Upload.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/service/MemberService.java
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: 🔨 Refactor, ⛲ Feature, 👽️ API

#98 ✨ feat : 액세스 토큰 디코딩 Utils 추가
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/payment/dto/Amount.java
  server/src/main/java/com/main21/payment/dto/CardInfo.java
  server/src/main/java/com/main21/payment/dto/PayApprovalDto.java
  server/src/main/java/com/main21/payment/dto/PayCancelDto.java
  server/src/main/java/com/main21/payment/dto/PayReadyDto.java
  server/src/main/java/com/main21/payment/dto/ReservationInfo.java
  server/src/main/java/com/main21/payment/outbox/event/OutBoxEventBuilder.java
  server/src/main/java/com/main21/payment/outbox/event/OutboxEvent.java
  server/src/main/java/com/main21/payment/outbox/event/ReserveCreated.java
  server/src/main/java/com/main21/payment/outbox/event/ReserveEventBuilder.java
  server/src/main/java/com/main21/payment/response/Message.java
  server/src/main/java/com/main21/payment/service/PaymentService.java
  server/src/main/java/com/main21/payment/utils/ObjectMapperUtil.java
  server/src/main/java/com/main21/payment/utils/PayConstants.java
  server/src/main/java/com/main21/security/config/SecurityConfig.java
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
Labels: ⛲ Feature

#101 ✨ feat : 마이페이지에서 등록한 리뷰 조회
  server/images/953848804234416.png
  server/images/953848814383500.png
  server/images/953848814553458.png
  server/images/953849308556708.png
  server/images/953849308875291.png
  server/images/953849308978875.png
  server/images/953850032612000.png
  server/images/953850032897666.png
  server/images/953850033000666.png
  server/images/953999481372791.png
  server/images/953999491132458.png
  server/images/953999491424291.png
  server/images/954529076560250.png
  server/images/954529086717875.png
  server/images/954529087052250.png
  server/images/954696226037750.png
  server/images/954696261308833.png
  server/images/954696261452625.png
  server/images/954894194592333.png
  server/images/954894207242291.png
  server/images/954894207870958.png
  server/images/955054439571666.png
  server/images/955054449318416.png
  server/images/955054449488875.png
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#102 ✨ feat : 결제 요청 url 전송 기능 추가
  server/src/main/java/com/main21/payment/service/PaymentService.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/dto/Amount.java
  server/src/main/java/com/main21/reserve/dto/CardInfo.java
  server/src/main/java/com/main21/reserve/dto/PayApprovalDto.java
  server/src/main/java/com/main21/reserve/dto/PayCancelDto.java
  server/src/main/java/com/main21/reserve/dto/PayReadyDto.java
  server/src/main/java/com/main21/reserve/dto/ReservationInfo.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/event/OutBoxEventBuilder.java
  server/src/main/java/com/main21/reserve/event/OutboxEvent.java
  server/src/main/java/com/main21/reserve/event/ReserveCreated.java
  server/src/main/java/com/main21/reserve/event/ReserveEventBuilder.java
  server/src/main/java/com/main21/reserve/response/Message.java
  server/src/main/java/com/main21/reserve/service/PaymentService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/reserve/utils/ObjectMapperUtil.java
  server/src/main/java/com/main21/reserve/utils/PayConstants.java
  server/src/main/java/com/main21/reserve/utils/ReserveConstants.java
Labels: ⛲ Feature, 👽️ API

#105 ✨ feat : Search 기능 구현
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java
  server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature, 👽️ API

#106 ♻️ refactor : 장소 상세검색 시 카테고리 리스트출력
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceResponseDto.java
  server/src/main/java/com/main21/place/service/PlaceCategoryService.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: 🔨 Refactor

#107 :sparkles: feat : 예약 기능 구현
  client/.eslintrc.js
  client/fake-server/db.json
  client/package-lock.json
  client/package.json
  client/src/atoms.js
  client/src/components/ReservationAsideBar.js
  client/src/components/ReservvationComponets/ReservationBottomButtons.js
  client/src/components/ReservvationComponets/ReservationCalander.js
  client/src/components/ReservvationComponets/ReservationCapacityHandler.js
  client/src/pages/Detail.js
  client/src/pages/Register.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#108 ✨ feat : 결제 승인 결과 리다이렉트 추가
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/service/PaymentService.java
  server/src/main/java/com/main21/reserve/utils/PayConstants.java
  server/src/main/java/com/main21/reserve/vo/AmountVO.java
  server/src/main/java/com/main21/reserve/vo/CardVO.java
  server/src/main/java/com/main21/reserve/vo/EmailKey.java
  server/src/main/java/com/main21/reserve/vo/OrderVO.java
  server/src/main/java/com/main21/reserve/vo/OutBox.java
  server/src/main/java/com/main21/reserve/vo/ReserveVO.java
Labels: ⛲ Feature, 👽️ API

#109 ✨ refactor : Reserve 응답 데이터 추가 및 정렬 변경
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/repository/ReserveRepositoryImpl.java
Labels: 🔨 Refactor

#110 ✨ refactor : Bookmark 응답 데이터 추가 및 정렬 변경
  server/src/main/java/com/main21/bookmark/dto/BookmarkDto.java
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepositoryImpl.java
Labels: 🔨 Refactor

#112 ✨ feat : nav, category 수정, 라우팅, detail 페이지 조립, nav 페이지 별 반응 구현
  client/.eslintrc.js
  client/src/App.js
  client/src/atoms.js
  client/src/components/Category.js
  client/src/components/Nav.js
  client/src/components/ReservationAsideBar.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/LogIn.js
  client/src/pages/Main.js
  client/src/pages/MyPage.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: ⛲ Feature

#113 ✨ refactor : Pagination 적용
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/repository/CustomReserveRepository.java
  server/src/main/java/com/main21/reserve/repository/ReserveRepositoryImpl.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#114 👽 api : 검색, 카테고리 api요청 엔드포인트 변경
  client/src/components/Category.js
Labels: ⛲ Feature

#115 ✨ feat : 마이페이지 컴포넌트 제작
  client/.eslintrc.js
  client/src/components/MyPageCategoryList.js
  client/src/components/MyPageComponent.js
  client/src/pages/MyPage.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#116 ✨ feat : 메인페이지 컴포넌트
  client/src/components/MainCompo.js
Labels: 🖼 HTML&CSS

#117 ♻️ refactor : 마이페이지 유저 정보 조회 리펙토링 (추후 프로필 이미지 추가 해야함)
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/repository/MemberRepository.java
  server/src/main/java/com/main21/member/service/MemberService.java
Labels: 🔨 Refactor, ⛲ Feature, 👽️ API

#120 ✨ feat : 상세페이지 리뷰 페이징 처리
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: 🔨 Refactor, ⛲ Feature, 👽️ API

#121 ✨ feat : 마이페이지 컴포넌트 수정
  client/src/components/Modal.js
  client/src/components/MyPageCategoryList.js
  client/src/components/MyPageComponent.js
  client/src/components/ReviewWrite.js
Labels: ⛲ Feature

#125 :sparkles: feat : 이미지 리사이징 구현
  client/package-lock.json
  client/package.json
  client/src/atoms.js
  client/src/components/RegisterComponents/RegisterCategory.js
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/components/ReservationComponets/ReservationAsideBar.js
  client/src/components/ReservationComponets/ReservationBottomButtons.js
  client/src/components/ReservationComponets/ReservationCalander.js
  client/src/components/ReservationComponets/ReservationCapacityHandler.js
  client/src/pages/Detail.js
  client/src/pages/Register.js
Labels: 🚨 BugFix, 🔨 Refactor, 🖼 HTML&CSS, ⛲ Feature

#126 ♻️ refactor : paymentService와 ReserveService 병합
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/service/PaymentService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/security/config/RedisConfig.java
  server/src/main/java/com/main21/security/config/SecurityConfig.java
  server/src/main/java/com/main21/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main21/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
  server/src/main/java/com/main21/security/utils/RedisUtils.java
Labels: 🔨 Refactor

#127 ✨ feat : best mbti batch 기능 추가
  server/build.gradle
  server/src/main/java/com/main21/ServerApplication.java
  server/src/main/java/com/main21/batch/entity/Best.java
  server/src/main/java/com/main21/batch/process/RankingProcess.java
  server/src/main/java/com/main21/batch/repository/BestRepository.java
  server/src/main/java/com/main21/batch/repository/CustomBestRepository.java
  server/src/main/java/com/main21/batch/repository/CustomBestRepositoryImpl.java
  server/src/main/java/com/main21/reserve/entity/MbtiCount.java
  server/src/main/java/com/main21/reserve/repository/MbtiCountRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature

#132 ✨ feat : 리뷰 수정하기 기능 추가
  client/fake-server/db.json
  client/src/components/MyPageCategoryList.js
  client/src/components/MyPageComponent.js
  client/src/components/ReviewWrite.js
Labels: 🚨 BugFix, ⛲ Feature

#134 ✨ feat : 글 수정 리코일 연결
  client/src/atoms.js
  client/src/components/Modal.js
  client/src/components/MyPageCategoryList.js
  client/src/components/MyPageComponent.js
Labels: ⛲ Feature

#137 Update README.md
  README.md
Labels: 🖼 HTML&CSS

#136 ✨ feat : detail, main 구현
  client/fake-server/db.json
  client/src/atoms.js
  client/src/components/Category.js
  client/src/components/Fade.js
  client/src/components/MainCompo.js
  client/src/components/Map.js
  client/src/components/Nav.js
  client/src/components/ReservationComponets/ReservationAsideBar.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/Main.js
Labels: ⛲ Feature

#138 ✨ feat : 마이페이지에서 작성한 리뷰 조회(페이징, 정렬처리)
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/review/repository/CustomReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#139 ✨ feat : BEST MBTI 조회 추가
  server/src/main/java/com/main21/batch/controller/BatchController.java
  server/src/main/java/com/main21/batch/dto/Mbti.java
  server/src/main/java/com/main21/batch/process/RankingProcess.java
  server/src/main/java/com/main21/batch/repository/BestRepository.java
  server/src/main/java/com/main21/batch/service/BatchService.java
  server/src/main/java/com/main21/place/repository/CustomPlaceRepository.java
  server/src/main/java/com/main21/place/repository/PlaceRepositoryImpl.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
Labels: ⛲ Feature

#140 ✨ feat : 카테고리 id 중복 수정
  client/src/atoms.js
  client/src/components/Category.js
  client/src/components/Nav.js
Labels: ⛲ Feature

#141 ✨ feat : hostingTime 엔티티 추가
  server/src/main/java/com/main21/reserve/entity/HostingTime.java
  server/src/main/java/com/main21/reserve/entity/TimeStatus.java
  server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java
  server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java
Labels: ⛲ Feature

#142 ♻️ refactor : Hosting Time 변수명 변경
  server/src/main/java/com/main21/batch/process/RankingProcess.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/reserve/entity/HostingTime.java
Labels: 🔨 Refactor

#143 ♻️ refactor : nav,mainpage,detailpage-view 변수 정리
  client/src/components/Category.js
  client/src/components/Fade.js
  client/src/components/MainCompo.js
  client/src/components/Map.js
  client/src/components/Nav.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/Main.js
Labels: 🔨 Refactor

#144 🐛 fix : 지도 400에러 수정
  client/src/components/Map.js
Labels: 🚨 BugFix

#145 ✨ feat :캐러셀 버튼 조작 수정
  client/src/components/Fade.js
Labels: 🚨 BugFix, 🖼 HTML&CSS

#147 ✨ feat : 유효성 검증 추가
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/place/dto/PlaceImageDto.java
  server/src/main/java/com/main21/place/dto/PlacePostDto.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/validator/NotSpace.java
  server/src/main/java/com/main21/validator/NotSpaceValidator.java
Labels: ⛲ Feature

#148 ✨ feat : 예약시간 생성 로직
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/entity/HostingTime.java
  server/src/main/java/com/main21/reserve/entity/TimeStatus.java
  server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java
  server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature

#149 :recycle: refactor 예약 오류 수정
  client/src/components/ReservationComponets/ReservationCalendar.js
Labels: 🚨 BugFix, 🔨 Refactor

#150 ✨ feat : 예약시간 생성 로직2
  server/src/main/java/com/main21/reserve/entity/TimeStatus.java
  server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java
  server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor, ⛲ Feature

#152 ♻️ refactor : 예약시 최대 수용 인원 초과 금지2
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#153 🐛 fix : Cancel repository 삭제
  server/src/main/java/com/main21/reserve/repository/CancelReasonRepository.java
Labels: 🔨 Refactor

#154 :recycle: refactor : 멘토링 후 코드 리팩토링
  client/src/components/RegisterComponents/RegisterCategory.js
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/components/ReservationComponents/ReservationCalendar.js
  client/src/components/ReservationComponents/ReservationCapacityHandler.js
  client/src/pages/Detail.js
  client/src/pages/LogIn.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: 🔨 Refactor

#155 ✨ feat : 예약 maxSpace 구현
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/repository/TimeStatusRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature, 👽️ API

#156 ✨ feat : Reserve Cancel 기능 구현
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/entity/CancelReason.java
  server/src/main/java/com/main21/reserve/repository/CancelReasonRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: ⛲ Feature

#157 ♻️ refactor: Reserve Cancel 기능 구현
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
Labels: 🔨 Refactor

#158 ♻️ refactor: reserve maxSpace 수정
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#161 :sparkles: feat : 로그인 통신 기능 구현
  client/fake-server/db.json
  client/src/pages/LogIn.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#162 ♻️ refactor : styled 위치 변경, 모듈 구분
  client/src/components/Category.js
  client/src/components/Fade.js
  client/src/components/Map.js
  client/src/components/Nav.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/Main.js
Labels: 🔨 Refactor

#163 ♻️ refactor : cookie -> redis 변경 (Member 도메인)
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/MemberDto.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/entity/MemberImage.java
  server/src/main/java/com/main21/member/entity/Token.java
  server/src/main/java/com/main21/member/repository/TokenRepository.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/member/service/MemberService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/security/config/SecurityConfig.java
  server/src/main/java/com/main21/security/dto/LoginDto.java
  server/src/main/java/com/main21/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main21/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/main21/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main21/security/utils/CookieUtils.java
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
  server/src/main/java/com/main21/security/utils/RedisUtils.java
  server/src/test/java/com/main21/config/SecurityTestConfig.java
  server/src/test/java/com/main21/controller/AuthControllerTest.java
  server/src/test/java/com/main21/controller/MemberControllerTest.java
  server/src/test/java/com/main21/utils/ApiDocumentUtils.java
Labels: 🔨 Refactor

#165 ♻️ refactor : 코드 익명함수 변경 및 함수 훅으로 분리작업
  client/src/components/MyPageCategoryList.js
  client/src/components/MyPageComponent.js
  client/src/components/useMyPage.js
Labels: 🔨 Refactor

#166 :sparkles: feat : 회원가입 통신 기능 구현
  client/fake-server/db.json
  client/src/App.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: ⛲ Feature

#167 ✨ feat : 글 수정 페이지 기능 구현
  client/src/atoms.js
  client/src/pages/Register.js
Labels: 🔨 Refactor, ⛲ Feature

#169 ♻️ refactor: Reserve Cancel 기능 수정 및 RefreshToken 적용
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/place/mapper/PlaceMapper.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/entity/MbtiCount.java
  server/src/main/java/com/main21/reserve/entity/TimeStatus.java
  server/src/main/java/com/main21/reserve/mapper/ReserveMapper.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#168 :recycle: refactor 체크된 카테고리 리스트 관리 함수 생성
  client/src/components/RegisterComponents/RegisterCategory.js
Labels: 🔨 Refactor

#170 ♻️ refactor: Reserve 도메인 RefreshToken 적용
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#172 ♻️ refactor : 함수 코드 리팩터링
  client/src/pages/Register.js
Labels: 🔨 Refactor

#174 ♻️ refactor: Bookmark 도메인 RefreshToken 적용
  server/src/main/java/com/main21/bookmark/controller/BookmarkController.java
  server/src/main/java/com/main21/bookmark/service/BookmarkService.java
Labels: 🔨 Refactor

#176 ♻️ refactor: Review 도메인 RefreshToken 적용
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: 🔨 Refactor, ⛲ Feature, 👽️ API

#177 ✨ feat : proxy 추가,route 변경
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Nav.js
  client/src/pages/Detail.js
  client/src/pages/Places.js
  client/src/setUpProxy.js
Labels: ⛲ Feature

#178 ♻️ refactor : security refactoring 작업 수행
  server/build.gradle
  server/src/main/java/com/main21/exception/ExceptionCode.java
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/controller/MemberController.java
  server/src/main/java/com/main21/member/dto/AuthDto.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/security/config/SecurityConfig.java
  server/src/main/java/com/main21/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/main21/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationFailureHandler.java
  server/src/main/java/com/main21/security/handler/MemberAuthenticationSuccessHandler.java
  server/src/main/java/com/main21/security/provider/JwtAuthenticationProvider.java
  server/src/main/java/com/main21/security/token/JwtAuthenticationToken.java
  server/src/main/java/com/main21/security/utils/AuthConstants.java
  server/src/main/java/com/main21/security/utils/JwtTokenUtils.java
  server/src/test/java/com/main21/config/EmbeddedRedisConfig.java
  server/src/test/java/com/main21/config/PasswordEncoderConfig.java
  server/src/test/java/com/main21/config/SecurityTestConfig.java
  server/src/test/java/com/main21/controller/AuthControllerTest.java
  server/src/test/java/com/main21/utils/AuthConstants.java
  server/src/test/java/com/main21/utils/WithMockCustomMember.java
  server/src/test/java/com/main21/utils/WithMockCustomMemberSercurityContextFactory.java
Labels: 🔨 Refactor

#179 ♻️ refactor : 반복되어 사용되는 메서드 공통화
  server/src/main/java/com/main21/common/CommonService.java
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/member/service/MemberService.java
Labels: 🔨 Refactor

#180 ♻️ refactor : 코드 리팩터링
  client/src/components/MyPageCategoryList.js
  client/src/components/ReviewWrite.js
  client/src/components/useMyPage.js
  client/src/pages/Register.js
Labels: 🔨 Refactor

#181 ✨ feat : 대여 종료시간 추가, 장소 삭제
  server/src/main/java/com/main21/bookmark/repository/BookmarkRepository.java
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/dto/PlacePostDto.java
  server/src/main/java/com/main21/place/dto/PlaceResponseDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/repository/PlaceCategoryRepository.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/repository/HostingTimeRepository.java
  server/src/main/java/com/main21/reserve/repository/ReserveRepository.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/review/repository/ReviewRepository.java
  server/src/main/java/com/main21/review/repository/ReviewRepositoryImpl.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#184 ✨ feat : 결제 진행중이 아니라면 리뷰 달지 못하는 로직 추가
  server/src/main/java/com/main21/reserve/repository/ReserveRepository.java
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#182 ♻️ refactor : nav 버튼 컴포넌트 분리
  client/src/App.js
  client/src/components/Nav.js
  client/src/components/NavButton.js
  client/src/components/NotFound.js
  client/src/components/Place.js
  client/src/pages/Places.js
Labels: ⛲ Feature

#186 ✨ feat : Place 도메인 refreshToken 추가, 해당 멤버만 호스팅 수정 가능한 로직 추가
  server/images/1309811929805791.png
  server/images/1309945239863250.png
  server/images/1310026950361166.png
  server/images/1310069576800166.png
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: ⛲ Feature, 👽️ API

#187 ♻️ refactor : 경로 이름 수정
  client/src/components/MyPageCategoryList.js
  client/src/components/useMyPage.js
Labels: 🔨 Refactor

#188 👽 api : signup,login api 연결
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
  client/src/setUpProxy.js
Labels: 👽️ API

#189 :bug: fix : 예약 종료날짜 오류 수정
  client/src/atoms.js
  client/src/components/ReservationComponents/ReservationCalendar.js
Labels: 🚨 BugFix

#190 "♻️ refactor : reserve, review service 공통화 작업"
  server/images/1309811929805791.png
  server/images/1309945239863250.png
  server/images/1310026950361166.png
  server/images/1310069576800166.png
  server/src/main/java/com/main21/common/CommonService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: 🔨 Refactor

#191 👽 api : api 주소값 변경
  client/src/components/MyPageCategoryList.js
  client/src/components/useMyPage.js
Labels: 🔨 Refactor, 👽️ API

#196 ✨ feat : Place 응답 데이터 추가 및 상세 페이지 조회 시 북마크 여부 구현
  server/src/main/java/com/main21/bookmark/controller/BookmarkController.java
  server/src/main/java/com/main21/bookmark/entity/Bookmark.java
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlaceResponseDto.java
  server/src/main/java/com/main21/place/service/PlaceService.java
Labels: 🔨 Refactor, ⛲ Feature

#197 ✨ feat : 상세페이지 내 리뷰 컴포넌트 제작
  client/src/components/Review.js
  client/src/components/ReviewContainer.js
  client/src/pages/Detail.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#198 :sparkles: 글 등록, 수정시 유효성 검사 기능 구현
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/pages/Register.js
  client/src/setUpProxy.js
Labels: ⛲ Feature

#200 👽 api : api 경로 수정
  client/src/components/Category.js
  client/src/components/Navigation.js/Nav.js
  client/src/components/Navigation.js/NavButton.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/View.js
  client/src/components/useMyPage.js
  client/src/hooks/getAllPlaces.js
  client/src/hooks/useAsync.js
  client/src/pages/Detail.js
  client/src/pages/LogIn.js
  client/src/pages/MyPage.js
  client/src/pages/Places.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
  client/src/setUpProxy.js
Labels: 👽️ API

#202 ♻️ refactor : 폴더이름 변경
  client/src/components/Navigation/Nav.js
  client/src/components/Navigation/NavButton.js
  client/src/pages/Detail.js
  client/src/pages/MyPage.js
  client/src/pages/Places.js
  client/src/pages/Register.js
Labels: 📄 Docs

#199 ♻️ refactor : MemberService 공통 메서드 분리
  server/build.gradle
  server/src/main/java/com/main21/ServerApplication.java
  server/src/main/java/com/main21/common/CommonService.java
  server/src/main/java/com/main21/member/controller/AuthController.java
  server/src/main/java/com/main21/member/entity/Member.java
  server/src/main/java/com/main21/member/entity/MemberImage.java
  server/src/main/java/com/main21/member/service/AuthService.java
  server/src/main/java/com/main21/member/service/MemberDbService.java
  server/src/main/java/com/main21/member/service/MemberService.java
  server/src/main/java/com/main21/reserve/dto/PayReadyDto.java
  server/src/main/java/com/main21/reserve/feign/DemoFeignInterceptor.java
  server/src/main/java/com/main21/reserve/feign/FeignConfig.java
  server/src/main/java/com/main21/reserve/feign/GithubDecoder.java
  server/src/main/java/com/main21/reserve/feign/KaKaoFeignClient.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/reserve/utils/KakaoInfo.java
  server/src/main/java/com/main21/reserve/utils/PayConstants.java
Labels: 🔨 Refactor

#203 :recycle: refactor : 폴더 이름 변경
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: 🔨 Refactor

#205 ♻️ refactor: Reserve service 분리
  server/src/main/java/com/main21/reserve/controller/ReserveController.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/service/CancelReasonService.java
  server/src/main/java/com/main21/reserve/service/HostingTimeService.java
  server/src/main/java/com/main21/reserve/service/MbtiCountService.java
  server/src/main/java/com/main21/reserve/service/ReserveDbService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor, ⛲ Feature

#206 ♻️ refactor: place 와 category 분리
  server/src/main/java/com/main21/place/service/PlaceCategoryService.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/java/com/main21/reserve/service/HostingTimeService.java
Labels: 🔨 Refactor

#207 ✨ feat : 마이페이지에서 리뷰 조회에서 대표이미지 추가
  server/src/main/java/com/main21/review/controller/ReviewController.java
  server/src/main/java/com/main21/review/dto/ReviewDto.java
  server/src/main/java/com/main21/review/service/ReviewDbService.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: ⛲ Feature, 👽️ API

#208 🐛 fix : 이미지파일 경로 수정
  server/src/main/java/com/main21/file/S3Upload.java
Labels: 🔨 Refactor

#210 :recycle: refactor 비밀번호 정규식 변경
  client/src/pages/Register.js
  client/src/pages/SignUp.js
  client/src/setUpProxy.js
Labels: 🔨 Refactor

#211 👽 api : api 연결
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/atoms.js
  client/src/components/Fade.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/View.js
  client/src/components/useMyPage.js
  client/src/index.js
  client/src/pages/Places.js
  client/src/pages/Register.js
  client/src/pages/SignUp.js
Labels: 👽️ API

#212 ♻️ refactor: DbService 분리 및 날짜 데이터 변경
  server/src/main/java/com/main21/place/controller/PlaceController.java
  server/src/main/java/com/main21/place/dto/PlacePostDto.java
  server/src/main/java/com/main21/place/service/PlaceDbService.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/java/com/main21/reserve/dto/ReserveDto.java
  server/src/main/java/com/main21/reserve/entity/Reserve.java
  server/src/main/java/com/main21/reserve/service/HostingTimeService.java
  server/src/main/java/com/main21/reserve/service/ReserveDbService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
  server/src/main/java/com/main21/review/service/ReviewDbService.java
  server/src/main/java/com/main21/review/service/ReviewService.java
Labels: 🔨 Refactor, ⛲ Feature

#213 ✨ feat : 리뷰 컨테이너 UI 완성 및 임시 api 연결
  client/src/components/Review.js
  client/src/components/ReviewContainer.js
  client/src/components/View.js
  client/src/components/useMyPage.js
Labels: 🖼 HTML&CSS, ⛲ Feature, 👽️ API

#214 ♻️ refactor: PlaceDto 수정 및 예약 등록 로직 수정
  server/src/main/java/com/main21/place/dto/PlaceDto.java
  server/src/main/java/com/main21/place/dto/PlacePatchDto.java
  server/src/main/java/com/main21/place/dto/PlacePostDto.java
  server/src/main/java/com/main21/place/entity/Place.java
  server/src/main/java/com/main21/place/service/PlaceService.java
  server/src/main/java/com/main21/reserve/service/HostingTimeService.java
  server/src/main/java/com/main21/reserve/service/ReserveService.java
Labels: 🔨 Refactor

#215 ✨ feat : 리뷰 컴포넌트 내 버튼 및 기능 수정
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/Review.js
Labels: 🖼 HTML&CSS, ⛲ Feature

#216 :recycle: refactor: 이미지 깨짐 현상 오류 수정
  client/package.json
  client/src/components/RegisterComponents/RegisterImages.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/pages/Register.js
Labels: 🔨 Refactor

#218 글 작성 완료시 메인페이지로 이동
  client/src/pages/Register.js
Labels: ⛲ Feature

#219 👽 api : api 수정
  client/src/components/Category.js
  client/src/components/Navigation/Nav.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/View.js
  client/src/pages/Places.js
Labels: 👽️ API

#221 👽 api : detail api 수정
  client/src/components/Fade.js
  client/src/components/ReservationComponents/ReservationAsideBar.js
  client/src/components/View.js
  client/src/pages/Detail.js
  client/src/pages/Places.js
Labels: 👽️ API

#222 :recycle: refactor: 천원 단위 표시
  client/src/components/ReservationComponents/ReservationAsideBar.js
Labels: 🔨 Refactor

#223 ✨ feat : 예약 내역 EmailSender 구현
  server/build.gradle
  server/src/main/java/com/main21/helper/MailController.java
  server/src/main/java/com/main21/helper/MailService.java
Labels: 🔨 Refactor, 👽️ API

#224 :sparkles: 회원가입 페이지 유효성 검사 수정
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/pages/SignUp.js
  client/src/utils/header.js
Labels: ⛲ Feature

#225 :recycle: 북마크 기능 수정
  client/src/components/ReservationComponents/ReservationBottomButtons.js
  client/src/pages/Detail.js
  client/src/setUpProxy.js
Labels: ⛲ Feature

#226 👽 api : 토큰 리이슈
  client/src/App.js
Labels: 👽️ API

#227 👽 api : 리뷰 관련 api 수정
  client/src/components/MyPageCategoryList.js
  client/src/components/ReviewWrite.js
  client/src/components/useMyPage.js
Labels: 👽️ API
